# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getScore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duibi_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('liangdu_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('qinggan_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('mohu_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('people_score', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='picture'),
        ),
    ]
