# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getScore', '0003_remove_picture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='duibi_score',
            new_name='duibi',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='liangdu_score',
            new_name='liangdu',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='mohu_score',
            new_name='mohu',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='people_score',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='qinggan_score',
            new_name='qinggan',
        ),
    ]
