# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getScore', '0004_auto_20171022_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
